.class public Lcom/android/settings/AGPSFunctionSwitchList;
.super Landroid/app/Activity;
.source "AGPSFunctionSwitchList.java"

# interfaces
.implements Landroid/view/View$OnClickListener;


# static fields
.field public static mSecProperties:Ljava/util/Properties;

.field private static mbtnAgpsDefaultValue:Landroid/widget/Button;


# instance fields
.field mRadioButton1:Landroid/widget/RadioButton;

.field mRadioButton2:Landroid/widget/RadioButton;

.field mRadioButton3:Landroid/widget/RadioButton;

.field private mtvAgpsDefaultValueNote:Landroid/widget/TextView;

.field private mtvAgpsDefaultValueTitle:Landroid/widget/TextView;


# direct methods
.method static constructor <clinit>()V
    .locals 1

    .prologue
    .line 33
    const/4 v0, 0x0

    sput-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mbtnAgpsDefaultValue:Landroid/widget/Button;

    return-void
.end method

.method public constructor <init>()V
    .locals 1

    .prologue
    const/4 v0, 0x0

    .line 25
    invoke-direct {p0}, Landroid/app/Activity;-><init>()V

    .line 34
    iput-object v0, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueTitle:Landroid/widget/TextView;

    .line 35
    iput-object v0, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueNote:Landroid/widget/TextView;

    return-void
.end method

.method private save()V
    .locals 5

    .prologue
    .line 265
    :try_start_0
    new-instance v1, Ljava/io/File;

    const-string v3, "/data/data/com.android.angryGps/secgps.conf"

    invoke-direct {v1, v3}, Ljava/io/File;-><init>(Ljava/lang/String;)V

    .line 267
    .local v1, file:Ljava/io/File;
    if-eqz v1, :cond_0

    .line 268
    new-instance v2, Ljava/io/FileOutputStream;

    invoke-direct {v2, v1}, Ljava/io/FileOutputStream;-><init>(Ljava/io/File;)V

    .line 270
    .local v2, stream:Ljava/io/FileOutputStream;
    sget-object v3, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v4, "Generated by AngryGPS & setting."

    invoke-virtual {v3, v2, v4}, Ljava/util/Properties;->store(Ljava/io/OutputStream;Ljava/lang/String;)V

    .line 271
    invoke-virtual {v2}, Ljava/io/FileOutputStream;->close()V
    :try_end_0
    .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_0

    .line 276
    .end local v1           #file:Ljava/io/File;
    .end local v2           #stream:Ljava/io/FileOutputStream;
    :cond_0
    :goto_0
    return-void

    .line 273
    :catch_0
    move-exception v0

    .line 274
    .local v0, e:Ljava/io/IOException;
    const-string v3, "AGPSFunctionSwitch"

    const-string v4, "Could not open GPS configuration file in save : /data/data/com.android.angryGps/secgps.conf"

    invoke-static {v3, v4}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    goto :goto_0
.end method

.method private setDefaultParameters()V
    .locals 3

    .prologue
    .line 281
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "OPERATION_MODE"

    const-string v2, "MSBASED"

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 287
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "SUPL_PORT"

    const/16 v2, 0x1c6b

    invoke-static {v2}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;

    move-result-object v2

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 289
    sget-object v0, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    const-string v1, "SUPL_HOST"

    const-string v2, "221.176.0.55"

    invoke-virtual {v0, v1, v2}, Ljava/util/Properties;->setProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;

    .line 296
    invoke-direct {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->save()V

    .line 297
    return-void
.end method


# virtual methods
.method public GPSSetDefaultVaule()V
    .locals 7

    .prologue
    .line 233
    const-string v5, "AGPSFunctionSwitch"

    const-string v6, "Load the configuration file"

    invoke-static {v5, v6}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 236
    const/4 v3, 0x0

    .line 237
    .local v3, fsuccess:Z
    new-instance v5, Ljava/util/Properties;

    invoke-direct {v5}, Ljava/util/Properties;-><init>()V

    sput-object v5, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    .line 240
    :try_start_0
    new-instance v5, Ljava/io/File;

    const-string v6, "/data/data/com.android.angryGps"

    invoke-direct {v5, v6}, Ljava/io/File;-><init>(Ljava/lang/String;)V

    invoke-virtual {v5}, Ljava/io/File;->mkdir()Z

    move-result v0

    .line 241
    .local v0, dirsuccess:Z
    if-eqz v0, :cond_2

    .line 242
    const-string v5, "AGPSFunctionSwitch"

    const-string v6, "Directory: /data/data/com.android.angryGps created"

    invoke-static {v5, v6}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 243
    new-instance v2, Ljava/io/File;

    const-string v5, "/data/data/com.android.angryGps/secgps.conf"

    invoke-direct {v2, v5}, Ljava/io/File;-><init>(Ljava/lang/String;)V

    .line 244
    .local v2, file:Ljava/io/File;
    if-eqz v2, :cond_0

    invoke-virtual {v2}, Ljava/io/File;->exists()Z

    move-result v5

    if-nez v5, :cond_0

    .line 245
    invoke-virtual {v2}, Ljava/io/File;->createNewFile()Z

    move-result v3

    .line 250
    :cond_0
    :goto_0
    if-eqz v2, :cond_1

    .line 251
    new-instance v4, Ljava/io/FileInputStream;

    invoke-direct {v4, v2}, Ljava/io/FileInputStream;-><init>(Ljava/io/File;)V

    .line 252
    .local v4, stream:Ljava/io/FileInputStream;
    sget-object v5, Lcom/android/settings/AGPSFunctionSwitchList;->mSecProperties:Ljava/util/Properties;

    invoke-virtual {v5, v4}, Ljava/util/Properties;->load(Ljava/io/InputStream;)V

    .line 253
    invoke-virtual {v4}, Ljava/io/FileInputStream;->close()V

    .line 255
    .end local v4           #stream:Ljava/io/FileInputStream;
    :cond_1
    invoke-direct {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->setDefaultParameters()V

    .line 260
    .end local v0           #dirsuccess:Z
    .end local v2           #file:Ljava/io/File;
    :goto_1
    return-void

    .line 248
    .restart local v0       #dirsuccess:Z
    :cond_2
    new-instance v2, Ljava/io/File;

    const-string v5, "/data/data/com.android.angryGps/secgps.conf"

    invoke-direct {v2, v5}, Ljava/io/File;-><init>(Ljava/lang/String;)V
    :try_end_0
    .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_0

    .restart local v2       #file:Ljava/io/File;
    goto :goto_0

    .line 256
    .end local v0           #dirsuccess:Z
    .end local v2           #file:Ljava/io/File;
    :catch_0
    move-exception v1

    .line 257
    .local v1, e:Ljava/io/IOException;
    const-string v5, "AGPSFunctionSwitch"

    const-string v6, "Could not open GPS configuration file in load : /data/data/com.android.angryGps/secgps.conf"

    invoke-static {v5, v6}, Landroid/util/Log;->w(Ljava/lang/String;Ljava/lang/String;)I

    .line 258
    invoke-direct {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->setDefaultParameters()V

    goto :goto_1
.end method

.method public onClick(Landroid/view/View;)V
    .locals 7
    .parameter "v"

    .prologue
    const/4 v6, 0x1

    const/4 v5, 0x0

    .line 140
    const/4 v1, 0x0

    .line 141
    .local v1, OperationTestMode:I
    const/4 v0, 0x0

    .line 143
    .local v0, OperationMode:I
    invoke-virtual {p1}, Landroid/view/View;->getId()I

    move-result v2

    packed-switch v2, :pswitch_data_0

    .line 213
    :pswitch_0
    const-string v2, "AGPSFunctionSwitch"

    const-string v3, "default"

    invoke-static {v2, v3}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 215
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 218
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 219
    if-nez v1, :cond_0

    .line 220
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 221
    if-nez v0, :cond_0

    .line 222
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 226
    :cond_0
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->finish()V

    .line 230
    :goto_0
    return-void

    .line 145
    :pswitch_1
    const-string v2, "AGPSFunctionSwitch"

    const-string v3, "agps_on_for_home_network"

    invoke-static {v2, v3}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 147
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 149
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 151
    if-nez v1, :cond_1

    .line 152
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 153
    if-nez v0, :cond_1

    .line 154
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 157
    :cond_1
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->finish()V

    goto :goto_0

    .line 161
    :pswitch_2
    const-string v2, "AGPSFunctionSwitch"

    const-string v3, "agps_on_for_all_network"

    invoke-static {v2, v3}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 163
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    const/4 v4, 0x2

    invoke-static {v2, v3, v4}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 165
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 167
    if-nez v1, :cond_2

    .line 168
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 169
    if-nez v0, :cond_2

    .line 170
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 173
    :cond_2
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->finish()V

    goto :goto_0

    .line 177
    :pswitch_3
    const-string v2, "AGPSFunctionSwitch"

    const-string v3, "agps_off"

    invoke-static {v2, v3}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 179
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    const/4 v4, 0x3

    invoke-static {v2, v3, v4}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 182
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 183
    if-nez v1, :cond_3

    .line 184
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 186
    :cond_3
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->finish()V

    goto/16 :goto_0

    .line 190
    :pswitch_4
    const-string v2, "AGPSFunctionSwitch"

    const-string v3, "agps_default_value"

    invoke-static {v2, v3}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 192
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "agps_function_switch"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 194
    const v2, 0x7f0b001f

    invoke-virtual {p0, v2}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v2

    check-cast v2, Landroid/widget/RadioButton;

    iput-object v2, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    .line 195
    iget-object v2, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    invoke-virtual {v2, v6}, Landroid/widget/RadioButton;->setChecked(Z)V

    .line 198
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationTestMode"

    invoke-static {v2, v3, v5}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v1

    .line 199
    if-nez v1, :cond_4

    .line 200
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "OperationMode"

    invoke-static {v2, v3, v6}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 203
    :cond_4
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "ServerCustomUrl"

    const-string v4, "221.176.0.55"

    invoke-static {v2, v3, v4}, Landroid/provider/Settings$System;->putString(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;)Z

    .line 204
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v2

    const-string v3, "ServerCustomPort"

    const/16 v4, 0x1c6b

    invoke-static {v2, v3, v4}, Landroid/provider/Settings$System;->putInt(Landroid/content/ContentResolver;Ljava/lang/String;I)Z

    .line 208
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->GPSSetDefaultVaule()V

    .line 209
    invoke-virtual {p1}, Landroid/view/View;->invalidate()V

    goto/16 :goto_0

    .line 143
    nop

    :pswitch_data_0
    .packed-switch 0x7f0b001f
        :pswitch_1
        :pswitch_2
        :pswitch_3
        :pswitch_0
        :pswitch_0
        :pswitch_4
    .end packed-switch
.end method

.method public onCreate(Landroid/os/Bundle;)V
    .locals 6
    .parameter "savedInstanceState"

    .prologue
    const/16 v5, 0x8

    const/4 v4, 0x1

    .line 70
    invoke-super {p0, p1}, Landroid/app/Activity;->onCreate(Landroid/os/Bundle;)V

    .line 71
    const v1, 0x7f040009

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->setContentView(I)V

    .line 74
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v1

    const-string v2, "agps_function_switch"

    invoke-static {v1, v2, v4}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 75
    .local v0, agps_function_switch_mode:I
    const-string v1, "AGPSFunctionSwitch"

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const-string v3, "onCreate : Settings AGPS_FUNCTION_SWITCH : "

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    invoke-static {v1, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 78
    const v1, 0x7f0b001f

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/RadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    .line 79
    const v1, 0x7f0b0020

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/RadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Landroid/widget/RadioButton;

    .line 80
    const v1, 0x7f0b0021

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/RadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Landroid/widget/RadioButton;

    .line 82
    const v1, 0x7f0b0024

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/Button;

    sput-object v1, Lcom/android/settings/AGPSFunctionSwitchList;->mbtnAgpsDefaultValue:Landroid/widget/Button;

    .line 83
    const v1, 0x7f0b0022

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/TextView;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueTitle:Landroid/widget/TextView;

    .line 84
    const v1, 0x7f0b0023

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/TextView;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueNote:Landroid/widget/TextView;

    .line 86
    packed-switch v0, :pswitch_data_0

    .line 97
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    invoke-virtual {v1, v4}, Landroid/widget/RadioButton;->setChecked(Z)V

    .line 101
    :goto_0
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    invoke-virtual {v1, p0}, Landroid/widget/RadioButton;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    .line 102
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Landroid/widget/RadioButton;

    invoke-virtual {v1, p0}, Landroid/widget/RadioButton;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    .line 103
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Landroid/widget/RadioButton;

    invoke-virtual {v1, p0}, Landroid/widget/RadioButton;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    .line 105
    sget-object v1, Lcom/android/settings/AGPSFunctionSwitchList;->mbtnAgpsDefaultValue:Landroid/widget/Button;

    invoke-virtual {v1, v5}, Landroid/widget/Button;->setVisibility(I)V

    .line 106
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueTitle:Landroid/widget/TextView;

    invoke-virtual {v1, v5}, Landroid/widget/TextView;->setVisibility(I)V

    .line 107
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mtvAgpsDefaultValueNote:Landroid/widget/TextView;

    invoke-virtual {v1, v5}, Landroid/widget/TextView;->setVisibility(I)V

    .line 108
    sget-object v1, Lcom/android/settings/AGPSFunctionSwitchList;->mbtnAgpsDefaultValue:Landroid/widget/Button;

    invoke-virtual {v1, p0}, Landroid/widget/Button;->setOnClickListener(Landroid/view/View$OnClickListener;)V

    .line 109
    return-void

    .line 88
    :pswitch_0
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    invoke-virtual {v1, v4}, Landroid/widget/RadioButton;->setChecked(Z)V

    goto :goto_0

    .line 91
    :pswitch_1
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Landroid/widget/RadioButton;

    invoke-virtual {v1, v4}, Landroid/widget/RadioButton;->setChecked(Z)V

    goto :goto_0

    .line 94
    :pswitch_2
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Landroid/widget/RadioButton;

    invoke-virtual {v1, v4}, Landroid/widget/RadioButton;->setChecked(Z)V

    goto :goto_0

    .line 86
    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_0
        :pswitch_1
        :pswitch_2
    .end packed-switch
.end method

.method protected onResume()V
    .locals 5

    .prologue
    const/4 v4, 0x1

    .line 113
    invoke-super {p0}, Landroid/app/Activity;->onResume()V

    .line 116
    invoke-virtual {p0}, Lcom/android/settings/AGPSFunctionSwitchList;->getContentResolver()Landroid/content/ContentResolver;

    move-result-object v1

    const-string v2, "agps_function_switch"

    invoke-static {v1, v2, v4}, Landroid/provider/Settings$System;->getInt(Landroid/content/ContentResolver;Ljava/lang/String;I)I

    move-result v0

    .line 117
    .local v0, agps_function_switch_mode:I
    const-string v1, "AGPSFunctionSwitch"

    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const-string v3, "onResume : Settings. AGPS_FUNCTION_SWITCH : "

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2, v0}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    invoke-static {v1, v2}, Landroid/util/Log;->d(Ljava/lang/String;Ljava/lang/String;)I

    .line 119
    const v1, 0x7f0b001f

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/RadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    .line 120
    const v1, 0x7f0b0020

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/RadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Landroid/widget/RadioButton;

    .line 121
    const v1, 0x7f0b0021

    invoke-virtual {p0, v1}, Lcom/android/settings/AGPSFunctionSwitchList;->findViewById(I)Landroid/view/View;

    move-result-object v1

    check-cast v1, Landroid/widget/RadioButton;

    iput-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Landroid/widget/RadioButton;

    .line 123
    packed-switch v0, :pswitch_data_0

    .line 134
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    invoke-virtual {v1, v4}, Landroid/widget/RadioButton;->setChecked(Z)V

    .line 137
    :goto_0
    return-void

    .line 125
    :pswitch_0
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton1:Landroid/widget/RadioButton;

    invoke-virtual {v1, v4}, Landroid/widget/RadioButton;->setChecked(Z)V

    goto :goto_0

    .line 128
    :pswitch_1
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton2:Landroid/widget/RadioButton;

    invoke-virtual {v1, v4}, Landroid/widget/RadioButton;->setChecked(Z)V

    goto :goto_0

    .line 131
    :pswitch_2
    iget-object v1, p0, Lcom/android/settings/AGPSFunctionSwitchList;->mRadioButton3:Landroid/widget/RadioButton;

    invoke-virtual {v1, v4}, Landroid/widget/RadioButton;->setChecked(Z)V

    goto :goto_0

    .line 123
    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_0
        :pswitch_1
        :pswitch_2
    .end packed-switch
.end method
